### ISSUE TITLE
[Bug] POST Request null Error

### ISSUE THREAD

**Issue by GamerMedic** [uncovery/Websend#3]
I've started to receive the following error:

https://pastebin.com/JR1gdgwU

I've not changed anything since the issues I had before ( issue  #2 ), and use of the minecraft /version command confirmed that I'm using version 5.2.

I've tried uninstalling and re-installing (making sure to update the config as appropriate) and I'm still getting the same issue.

EDIT:

The plugin works as expected if the command is sent from the console, or using another plugin (CustomCommands) to execute the command (though it's worth noting that CustomCommands executes from the console). In-game, however, I get the "An internal error occurred while attempting to perform this command" error, and the error in the console as posted in the PasteBin.

**Comment by uncovery** [comment]
Most likely you are running an outdated Minecraft server version. Please note that 5.2 is tied to at least 1.16.3, ideally 1.16.4. If you look at the lowest "Caused by..." in the log you will see that it's looking for 

`INFO Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_16_R3.inventory.CraftItemStack`

IIRC, you are using 1.1.6.2. That `v1_16_R3` refers to 1.16.3 and this library does not exist in 1.16.2. Newer versions (1.16.4 and 1.16.5) still use the R3 libraries. So if you update to 1.16.3, all versions released here (until now at least) should be working. This is something that the spigot/paper teams are managing and I am not in control of it.

The library in question is used to read the player inventory and therefore does not throw a fit when you run it from the console since there is no inventory.

**Comment by GamerMedic** [comment]
Ah, I see. I am running 1.16.2.

Thanks, I'll update.
